@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json


POST {{host}}/api/users/login
Content-Type: {{contentType}} 

{
   "email": "kiran@ojha.com",
   "password": "123456"
}

###
POST {{host}}/api/users/register
Content-Type: {{contentType}} 

{
   "name": "Kiran Ojha",
   "email": "kiran@ojha.com",
   "password": "123456"
}